add CD

diff --git a/cloudbuild.yml b/cloudbuild.yml
--- a/cloudbuild.yml
+++ b/cloudbuild.yml
@@ -18,15 +18,22 @@ steps:
     ./install.sh &&
     source .venv/bin/activate &&
     pytest .
-#- name: "noobzik/uv-gcp-cloud-build"
-#  id: CD
-#  entrypoint: /bin/bash
-#  args:
-#  - -c
-#  - 'chmod a+x install.sh && ./install.sh && kedro run --pipeline global'
-#  env:
-#  - 'ENV=$BRANCH_NAME'
-#  - 'MLFLOW_SERVER=$_MLFLOW_SERVER'
+- name: "noobzik/uv-gcp-cloud-build"
+  id: CD
+  entrypoint: /bin/bash
+  args:
+  - -c
+  - |
+    echo "$$SERVICE_ACCOUNT" > service_account.json
+    if ! gcloud auth activate-service-account --key-file=service_account.json; then
+      echo "ERROR: gcloud authenfication failed!"
+      exit 1
+    fi
+    gcloud config set project "$PROJECT_ID"
+    chmod a+x install.sh && ./install.sh && source .venv/bin/activate && kedro run
+  env:
+  - 'ENV=$BRANCH_NAME'
+  - 'MLFLOW_SERVER=$_MLFLOW_SERVER'
 
 logs_bucket: gs://purchase_predict
 availableSecrets:
