hotfix ?3

diff --git a/cloudbuild.yml b/cloudbuild.yml
--- a/cloudbuild.yml
+++ b/cloudbuild.yml
@@ -9,7 +9,12 @@ steps:
   - -c
   - |
     echo "$SERVICE_ACCOUNT" | base64 -d > service_account.json
-    gcloud auth activate-service-account --key-file=service_account.json
+    head -n 5 service_account.json
+    
+    if ! gcloud auth activate-service-account --key-file=service_account.json; then
+      echo "ERROR: gcloud authenfication failed!"
+      exit 1
+    fi
     gcloud config set project "$PROJECT_ID"
     chmod a+x install.sh && 
     ./install.sh &&
